apiVersion: apps/v1
kind: Deployment
metadata:
  name: restoactif-gitops
  namespace: laravel
spec:
  replicas: 2
  selector:
    matchLabels: { app: restoactif-gitops }
  template:
    metadata:
      labels: { app: restoactif-gitops }
    spec:
      containers:
      - name: app
        image: bayord/restoactif-gitops:71e4ca0dadc16eaa5dc506834d7bd83d78fa2e50
        ports: [{ containerPort: 80 }]
        envFrom:
        - configMapRef: { name: laravel-config }
        - secretRef: { name: laravel-secret }
        livenessProbe:
          httpGet: { path: /, port: 80 }
          initialDelaySeconds: 30
        readinessProbe:
          httpGet: { path: /, port: 80 }
          initialDelaySeconds: 10
        resources:
          requests: { cpu: 100m, memory: 256Mi }
          limits: { cpu: 500m, memory: 512Mi }