apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: laravel
type: Opaque
stringData:
  APP_KEY: "base64:27WeP4hrAbQLgEJyP3TdgkzOKZkOoyTxX+qcH35E5f8="
  DB_USERNAME: "laravel"
  DB_PASSWORD: "change-me-please"