apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: laravel
type: Opaque
stringData:
  APP_KEY: "base64:GENERE_AVEC_php_artisan_key:generate"
  DB_USERNAME: "laravel"
  DB_PASSWORD: "change-me-please"